

server:
  port: 8001
spring:
  application:
    name: project-XFC
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/digital reform project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  type-aliases-package: com.xfc.project_xfc.entity # 所有Entity别名类所在包
  mapper-locations: classpath:mapper/*.xml